// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace PluginManager.Data.Models
{
    public partial class Folder
    {
        [Key]
        [Column("Folder Id")]
        public long FolderId { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string FolderName { get; set; }
        [Column(TypeName = "bigint")]
        public long? PackageId { get; set; }
        [Column(TypeName = "bigint")]
        public bool IsHidden { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public DateTime InstallDate { get; set; }

        [ForeignKey(nameof(PackageId))]
        [InverseProperty(nameof(ZipFile.Folders))]
        public virtual ZipFile Package { get; set; }
    }
}