// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PluginManager.Data.Models.Configurations;
using System;

#nullable disable

namespace PluginManager.Data.Models
{
    public partial class PmDb : DbContext
    {
        public PmDb()
        {
        }

        public PmDb(DbContextOptions<PmDb> options)
            : base(options)
        {
        }

        public virtual DbSet<Folder> Folders { get; set; }
        public virtual DbSet<ZipFile> ZipFiles { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.FolderConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ZipFileConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
