// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace PluginManager.Data.Models
{
    public partial class ZipFile
    {
        public ZipFile()
        {
            Folders = new HashSet<Folder>();
        }

        [Key]
        public long PackageId { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string Filename { get; set; }
        [Column(TypeName = "text")]
        public string AddonName { get; set; }
        [Column(TypeName = "text")]
        public string Version { get; set; }
        [Column(TypeName = "bigint")]
        public long FileSize { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public DateTime FileDate { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public DateTime AddedDate { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string FilePath { get; set; }

        [InverseProperty(nameof(Folder.Package))]
        public virtual ICollection<Folder> Folders { get; set; }
    }
}