// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PluginManager.Data.Models;
using System;


namespace PluginManager.Data.Models.Configurations
{
    public partial class ZipFileConfiguration : IEntityTypeConfiguration<ZipFile>
    {
        public void Configure(EntityTypeBuilder<ZipFile> entity)
        {
            entity.Property(e => e.AddedDate).HasDefaultValueSql("datetime('now')");

            entity.Property(e => e.FileDate).HasDefaultValueSql("datetime('now')");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ZipFile> entity);
    }
}
